FROM node:24-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci
COPY . .
RUN npm run build

################################################
FROM nginx:1.25-alpine

RUN rm /etc/nginx/conf.d/default.conf
COPY nginx/default-prod.conf /etc/nginx/conf.d/default.conf
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# 빌드 결과물만 nginx 정적 파일 경로에 복사
COPY --from=build /app/build /usr/share/nginx/html

EXPOSE 30000

# nginx 실행
ENTRYPOINT ["nginx", "-g", "daemon off;"]